-- ==============================================================================
-- Supabase Baseline Migration: 20260912001600_remote_schema.sql
-- Pulled Date: 2026-09-12
-- Audit Finding M1 Resolution: Confirmed table name is 'print_job' (singular).
-- Detailed Documentation & Diffs: See /docs/other/schema-diff.md and /supabase/BASELINE_NOTES.md
-- ==============================================================================

CREATE TABLE "public"."order_items" (
  "id"                 uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "order_id"           uuid                     DEFAULT gen_random_uuid(),
  "product_id"         uuid                     DEFAULT gen_random_uuid(),
  "quantity"           bigint                   NOT NULL,
  "unit_price_at_sale" double precision,
  "subtotal"           double precision,
  "created_at"         timestamp with time zone NOT NULL DEFAULT now(),
  "profit"             double precision,
  CONSTRAINT "order_items_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."order_items"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."orders" (
  "id"              uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "total"           double precision         NOT NULL,
  "status"          text                     NOT NULL,
  "partial_payment" double precision,
  "created_at"      timestamp with time zone DEFAULT now(),
  "updated_at"      timestamp with time zone DEFAULT now(),
  "total_profit"    double precision,
  CONSTRAINT "orders_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."orders"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."print_job" (
  "id"           uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "order_id"     uuid                     DEFAULT gen_random_uuid(),
  "service_type" text,
  "paper_type"   text,
  "paper_size"   text,
  "color_mode"   text,
  "page_count"   bigint,
  "copies"       bigint,
  "subtotal"     double precision,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "print_job_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."print_job"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."products" (
  "id"               uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "name"             text,
  "quantity"         bigint                   NOT NULL,
  "price"            double precision,
  "created_at"       timestamp with time zone NOT NULL DEFAULT now(),
  "category"         text,
  "stock_threshhold" bigint                   NOT NULL,
  "cost"             double precision,
  "updated_at"       timestamp with time zone DEFAULT now(),
  CONSTRAINT "products_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."products"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."service_rates" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."print_rates_id_seq") NOT NULL,
  "service_type" text,
  "paper_type"   text,
  "paper_size"   text,
  "color_mode"   text,
  "price"        double precision,
  "created_at"   timestamp with time zone DEFAULT now(),
  "updated_at"   timestamp with time zone DEFAULT now(),
  "profit"       double precision,
  CONSTRAINT "print_rates_id_key" UNIQUE (id),
  CONSTRAINT "print_rates_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."service_rates"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."order_items"
  ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."print_job"
  ADD CONSTRAINT "print_job_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."order_items"
  ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE VIEW "public"."unique_categories" WITH (security_invoker=on) AS  SELECT DISTINCT category
   FROM public.products;

CREATE POLICY "Enable delete for all authenticated users" ON "public"."order_items"
  FOR DELETE
  TO "authenticated"
  USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."order_items"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Enable read access to all authenticated users" ON "public"."order_items"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Enable delete for authenticated users" ON "public"."orders"
  FOR DELETE
  TO "authenticated"
  USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."orders"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Enable read access for all authenticated users" ON "public"."orders"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Enable delete for authenticated users" ON "public"."print_job"
  FOR DELETE
  TO PUBLIC
  USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."print_job"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Enable read access for all authenticated users" ON "public"."print_job"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Allow authenticated user to update table" ON "public"."products"
  FOR UPDATE
  TO "authenticated"
  USING (true);

CREATE POLICY "Enable delete for authenticated" ON "public"."products"
  FOR DELETE
  TO "authenticated"
  USING (true);

CREATE POLICY "Enable insert for admin users only" ON "public"."products"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Enable read access for all authenticated users" ON "public"."products"
  FOR SELECT
  TO "authenticated"
  USING (true);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."order_items" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."orders" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."print_job" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."products" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."service_rates" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."unique_categories" TO "anon", "authenticated", "postgres", "service_role";

